###############################################################
### MÓDULO RESERVAS
### Estado: ✅ Completado
### Última actualización: 01/08/2026
###############################################################

###############################################################
### CREAR RESERVAS
###############################################################

### Crear reserva vinculada a cliente
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 5,
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-11-02",
  "fechaSalida": "2026-11-12"
}

### Crear reserva 2
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "SUITE",
  "fechaEntrada": "2026-10-02",
  "fechaSalida": "2026-10-12"
}

### Crear reserva hotel 2
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 6,
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-08-23",
  "fechaSalida": "2026-08-31"
}

### Comprobar que no muestra disponibilidad cuando todas las habitaciones están ocupadas esa fecha

### Crear reserva hotel 2
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-10-02",
  "fechaSalida": "2026-10-10"
}

### Crear reserva hotel 2
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-10-02",
  "fechaSalida": "2026-10-07"
}

### Crear reserva hotel 2
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-10-03",
  "fechaSalida": "2026-10-11"
}

### Confirmar reserva PENDIENTE 
PUT http://localhost:8080/api/reservas/27/confirmar

### Reserva ya CANCELADA
PUT http://localhost:8080/api/reservas/13/confirmar

###############################################################
### CONSULTAR RESERVAS
###############################################################

### Obtener todas las reservas
GET http://localhost:8080/api/reservas

###

### Obtener todas las habitaciones del hotel 1
GET http://localhost:8080/api/habitaciones/hotel/1

### Obtener reserva por id reserva
GET http://localhost:8080/api/reservas/20

###

### Obtener reservas de un hotel
GET http://localhost:8080/api/reservas/hotel/1

###

### Obtener reservas de una habitación
GET http://localhost:8080/api/reservas/habitacion/24

###

### Ver disponibilidad reserva por fecha, hotel y tipo de habitación
GET http://localhost:8080/api/reservas/probar-disponibilidad

###

###############################################################
### CANCELAR RESERVAS
###############################################################

### Cancelar reserva
DELETE http://localhost:8080/api/reservas/2

###

### Comprobar que la habitación vuelve a estar disponible
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "hotelId": 1,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-08-15",
  "fechaSalida": "2026-08-18"
}

###

###############################################################
### CASOS DE ERROR
###############################################################

### Hotel inexistente
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "hotelId": 999,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-08-15",
  "fechaSalida": "2026-08-18"
}

###

### Tipo de habitación inexistente en el hotel
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "hotelId": 2,
  "tipoHabitacion": "SUITE",
  "fechaEntrada": "2026-08-15",
  "fechaSalida": "2026-08-18"
}

###

### Fechas incorrectas
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "hotelId": 2,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-08-20",
  "fechaSalida": "2026-08-18"
}

###

### Incluir fecha de creación de la reserva
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "SUITE",
  "fechaEntrada": "2026-10-15",
  "fechaSalida": "2026-10-18"
}

### Nueva reserva con fecha de creación 
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-09-20",
  "fechaSalida": "2026-09-23"
}

### Nueva reserva con fecha de creación 
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "INDIVIDUAL",
  "fechaEntrada": "2026-09-10",
  "fechaSalida": "2026-09-13"
}

### Confirmación normal
PUT http://localhost:8080/api/reservas/ID/confirmar

### Reserva cancelada no se puede confirmar
PUT http://localhost:8080/api/reservas/13/confirmar

### Reserva inexistente
GET http://localhost:8080/api/reservas/999

###

### Confirmar una reserva PENDIENTE
PUT http://localhost:8080/api/reservas/11/confirmar

###

### Confirmar una reserva CONFIRMADA
PUT http://localhost:8080/api/reservas/7/confirmar

###

### Confirmar una reserva CANCELADA
PUT http://localhost:8080/api/reservas/2/confirmar

###

### Confirmar una reserva INEXISTENTE
PUT http://localhost:8080/api/reservas/999/confirmar

###

### Cliente con reserva PENDIENTE → cambiar DNI
PUT http://localhost:8080/api/clientes/5
Content-Type: application/json

{
  "dni": "11111111C",
  "nombre": "Juan",
  "apellidos": "Pérez García",
  "email": "juan.perez@email.com",
  "telefono": "600111222",
  "nacionalidad": "España",
  "formaPago": "TARJETA"
}

### Cliente con reserva CONFIRMADA → cambiar DNI
PUT http://localhost:8080/api/clientes/5
Content-Type: application/json

{
  "dni": "44111111C",
  "nombre": "Juan",
  "apellidos": "Pérez García",
  "email": "juan.perez@email.com",
  "telefono": "600111222",
  "nacionalidad": "España",
  "formaPago": "TARJETA"
}

### Cliente con reserva CONFIRMADA → cambiar otro dato
PUT http://localhost:8080/api/clientes/5
Content-Type: application/json

{
  "dni": "11111111C",
  "nombre": "Juan",
  "apellidos": "Pérez Salmerón",
  "email": "juan.perez@email.com",
  "telefono": "600111222",
  "nacionalidad": "España",
  "formaPago": "TARJETA"
}

### Crear reserva para prueba de cancelación
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-10-15",
  "fechaSalida": "2026-10-18"
}

### Confirmar reserva
PUT http://localhost:8080/api/reservas/19/confirmar

### Cancelar reserva confirmada dentro de plazo (48h antes de fecha de entrada)
PUT http://localhost:8080/api/reservas/19/cancelar

### Crear reserva - menos de 48h
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "DOBLE",
  "fechaEntrada": "2026-08-18",
  "fechaSalida": "2026-08-20"
}

### Confirmar reserva
PUT http://localhost:8080/api/reservas/20/confirmar

### Cancelar reserva fuera de plazo
PUT http://localhost:8080/api/reservas/20/cancelar

### Crear reserva PENDIENTE
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "clienteId": 1,
  "hotelId": 1,
  "tipoHabitacion": "INDIVIDUAL",
  "fechaEntrada": "2026-09-18",
  "fechaSalida": "2026-09-20"
}

### Cancelar reserva PENDIENTE
PUT http://localhost:8080/api/reservas/21/cancelar

### Cancelar reserva CANCELADA
PUT http://localhost:8080/api/reservas/19/cancelar

### Cancelar reserva inexistente
PUT http://localhost:8080/api/reservas/9999/cancelar


### Actualizar fechas reserva pendiente
PATCH http://localhost:8080/api/reservas/26
Content-Type: application/json

{
  "fechaEntrada": "2026-09-10",
  "fechaSalida": "2026-09-15"
}

### Actualizar tipo habitación reserva pendiente
PATCH http://localhost:8080/api/reservas/26
Content-Type: application/json

{
  "tipoHabitacion": "INDIVIDUAL"
}

### Actualizar cliente reserva pendiente
PATCH http://localhost:8080/api/reservas/26
Content-Type: application/json

{
  "clienteId": 7
}

### Actualizar tipo habitación reserva confirmada
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{
  "tipoHabitacion": "DOBLE"
}

### Actualizar fechas reserva confirmada >48h
PATCH http://localhost:8080/api/reservas/27
Content-Type: application/json

{
  "fechaEntrada": "2026-10-10",
  "fechaSalida": "2026-10-15"
}

### Actualizar fechas reserva confirmada <48h
PATCH http://localhost:8080/api/reservas/ID
Content-Type: application/json

{
  "fechaEntrada": "2026-08-23",
  "fechaSalida": "2026-08-25"
}

### Actualizar hotel reserva confirmada <48h
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{
  "hotelId": 2
}

### Actualizar cliente reserva confirmada
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{
  "clienteId": 3
}

### Actualizar reserva cancelada
PATCH http://localhost:8080/api/reservas/21
Content-Type: application/json

{
  "clienteId": 3
}

### Error validación: Request vacío
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{}

### Error validación: Sólo 1 fecha
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{
  "fechaEntrada": "2026-09-10"
}

### Error validación: cliente inexistente
PATCH http://localhost:8080/api/reservas/17
Content-Type: application/json

{
  "clienteId": 9999
}