spring.application.name=hotel-api

# Base de datos H2
spring.datasource.url=jdbc:h2:./hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
